#! /bin/bash
export PATH=/usr/local/bin:/usr/bin:$PATH
#./scopex -f SingleStep.scp -lscopex.log
# ./scopex -f Intercept2.scp -lscopex.log
# 
#./scopex -f Straight.scp -lscopex.log
# Check buoyancy:
./scopex -f Climb.scp -lscopex.log
